// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/gento?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/gento?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-ocp: https://img.shields.io/badge/openshift---?color=gray&logo=redhatopenshift&logoColor=red&style=flat
:img-rh: https://img.shields.io/badge/red%20hat---?color=gray&logo=redhat&logoColor=red&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/gento?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test: https://github.com/rdavid/gento/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-cv: http://cv.rabkin.co.il
:url-dci: https://github.com/redhat-cip/dci-openshift-app-agent
:url-gento: https://github.com/rdavid/gento/blob/master/app/gento
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-hadolint: https://github.com/hadolint/hadolint
:url-hoc: https://hitsofcode.com/view/github/rdavid/gento?branch=master
:url-install: https://github.com/rdavid/gento/blob/master/app/install
:url-license: https://github.com/rdavid/gento/blob/master/LICENSES/0BSD.txt
:url-ocp: https://www.redhat.com/en/technologies/cloud-computing/openshift
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/gento/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-rh: https://www.redhat.com
:url-shellbase: https://github.com/rdavid/shellbase
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shfmt: https://github.com/mvdan/sh
:url-test: https://github.com/rdavid/gento/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-zizmor: https://github.com/zizmorcore/zizmor

= Gento

[subs=attributes+]
++++
<div align="right">
<a href="{url-test}"><img src="{img-test}" alt="test"></a>
<a href="{url-hoc}"><img src="{img-hoc}" alt="hits of code"></a>
<a href="{url-releases}"><img src="{img-releases}" alt="release"></a>
<a href="{url-rh}"><img src="{img-rh}" alt="red hat"></a>
<a href="{url-ocp}"><img src="{img-ocp}" alt="openshift"></a>
<a href="{url-license}"><img src="{img-license}" alt="license"></a>
</div>
++++

toc::[]

ifdef::pages-build[]
++++
<div id="repo-link">
  <a href="https://github.com/rdavid/gento" aria-label="GitHub repository" target="_blank" rel="noopener">
    <svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true">
      <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/>
    </svg>
  </a>
</div>
++++
endif::[]

== About

Gento stands for `aGent of Red Hat OpenShift`.
It enables Cloud-Native Applications and Operators in OpenShift through the
{url-dci}[DCI OpenShift App Agent], part of the Red Hat Distributed
Continuous Integration (DCI) service.

== Install

Gento ships as a standalone Portable Operating System Interface (POSIX)
shell script named {url-gento}[`gento`].
Install it from the official {url-releases}[releases].
Writing to `/usr/local/bin` on Red Hat Enterprise Linux (RHEL) requires
administrative privileges, so prefix the `tar` command with `sudo`.

[,sh]
----
REL=0.9.20260404
SRC=https://github.com/rdavid/gento/archive/refs/tags/v$REL.tar.gz
curl --location --silent $SRC |
  sudo tar \
    --directory /usr/local/bin \
    --extract \
    --gzip \
    --strip-components=2 \
    gento-$REL/app/gento
----

To install {url-gento}[`gento`] with all its dependencies, run the
{url-install}[`install`] shell script as `root`:

[,sh]
----
REL=0.9.20260404
SRC=https://github.com/rdavid/gento/archive/refs/tags/v$REL.tar.gz
sudo su -c eval -c "$(
  curl --location --silent $SRC |
    tar \
      --extract \
      --gzip \
      --to-stdout \
      gento-$REL/app/install
)"
----

Run {url-gento}[`gento`] as the `dci-openshift-app-agent` user.
The parameter is a DCI settings file.
For better reporting, use the naming pattern `settings-cnf-name.yml`.
Make sure `/usr/local/bin` is in the `dci-openshift-app-agent` user's `PATH`.

[,sh]
----
sudo su - dci-openshift-app-agent
gento settings-cnf-name.yml
----

== Test

The project uses Daniel J. Bernstein's build system, {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-hadolint}[`hadolint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].

== License

Copyright {url-cv}[David Rabkin], released under the
{url-license}[Zero-Clause BSD license].

ifdef::pages-build[]
++++
<footer id="site-footer">
  <div class="footer-left">
    <img src="favicon.svg" alt="" width="20" height="20">
    <span>gento by <a href="http://cv.rabkin.co.il" target="_blank" rel="noopener">David Rabkin</a></span>
  </div>
  <div class="footer-links">
    <a href="https://github.com/rdavid/gento" target="_blank" rel="noopener">GitHub</a>
    <a href="https://github.com/rdavid/gento/releases" target="_blank" rel="noopener">Releases</a>
    <a href="https://github.com/rdavid/gento/blob/master/LICENSES/0BSD.txt" target="_blank" rel="noopener">0BSD License</a>
  </div>
</footer>
++++
endif::[]
