# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
version = 1
[[annotations]]
path = [
	".DS_Store",
	".github/styles/**",
	".gitignore",
	".vale.ini",
	"lint",
	"README.adoc",
]
precedence = "override"
SPDX-FileCopyrightText = "2025 David Rabkin"
SPDX-License-Identifier = "0BSD"
