---
name: linters
'on': push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml cfg
          strict: true
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: app/*
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d app/* cfg/*.sh
