# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: test
'on':
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - run: |
          brew install \
            asciidoctor \
            goredo \
            reuse \
            shellcheck \
            shfmt \
            typos-cli \
            vale \
            yamllint
          rel=0.9.20260707
          src=https://github.com/rdavid/shellbase/archive/refs/tags
          curl \
            --location \
            --silent \
            "$src"/v"$rel".tar.gz |
            tar \
              --directory /usr/local/bin \
              --extract \
              --gzip \
              --strip-components=2 \
              shellbase-"$rel"/lib/base.sh
          redo -xx
