# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: vale
'on':
  push:
    branches: [master]
  pull_request:
permissions:
  contents: read
  pull-requests: write
  checks: write
jobs:
  vale:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/cache@v5.0.5
        with:
          path: .github/styles
          key: vale-styles-${{ hashFiles('.vale.ini') }}
          restore-keys: vale-styles-
      - run: sudo apt-get install --no-install-recommends asciidoctor
      - uses: vale-cli/vale-action@2.1.2
        with:
          fail_on_error: true
